spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/animals_db
    username: postgres
    password: Hj78fv2005
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog-master.yml
    enabled: true